version: "3.8"
services:

  angular:
    image: finances-app-image
    container_name: finances-app-container
    depends_on: 
      - api
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    ports:
      - 8090:80

  api:
    image: api-image
    container_name: api-container
    depends_on: 
      - database
      - minio
    build:
      context: ./asp-web-api/Web-API
      dockerfile: Dockerfile
    ports:
      - 7132:80

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
    volumes:
      - ./sql-data/data:/var/opt/mssql/data
      - ./sql-data/log:/var/opt/mssql/log
      - ./sql-data/secrets:/var/opt/mssql/secrets
    user: root

  minio:
    image: minio/minio:latest
    container_name: minio-container
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio-storage:/data